### ISSUE TITLE
'x' is NULL error in null model loop

### ISSUE THREAD

**Issue by mvannuland** [cherren8/Cohesion#3]
Hi Christina,

I really enjoyed reading your recent article on the cohesion metric, and am trying to apply it to one of my datasets but get the following error well running the null model loop. It gets through about 80 steps before quitting with:

'x' is NULL so the result will be NULLError in ans[test & ok] <- rep(yes, length.out = length(ans))[test & ok] : replacement has length zero

I'm using rel abundance data with 30 samples and 100 taxa, none of the samples have 0 taxa, and it's not a very sparse table. Any thoughts on how to troubleshoot? Thanks very much!

**Comment by cherren8** [comment]
Hi Michael, 

Thanks for your question. Are you using the script version found with the ISME article, or from github? When R updated, there was a minor change in the ifelse() function, which is the source of the error. I thought that the version on github had solved that problem, but let me know if it hasn't! 

In any case, the error seems to originate from the fact that the last piece of code executed in the ifelse() statement if an if() statement. If you just comment out the if() statement, which is the counter for how the loop is progressing, it should run fine. 

Please let me know if this does not resolve the problem, or if you have any other questions!

Best, 

Cristina

**Comment by mvannuland** [comment]
That works! I had been trying the ISME version, but v1.1 on github worked great. Thanks again!
